### ISSUE TITLE
Installation problems with gyp already installed

### ISSUE THREAD

**Issue by ChristianRinn** [willwhitney/hydrogen#104]
Hey,

I ran into problems during installation of hydrogen via the terminal on my Kubuntu 14.04 machine.

tl;dr: I had already installed another version of gyp on my system and (temporarily) removing it via 
`sudo apt-get remove gyp` solved the problem for me.

The error message is almost exactly the same as this one: https://github.com/unitech/pm2/issues/434

```
apm install hydrogen    
Installing hydrogen to /home/christian/.atom/packages

> zmq@2.13.0 install /tmp/user/1000/apm-install-dir-11588-16981-1ijtnlc/node_modules/Hydrogen/node_modules/zmq
> node-gyp rebuild


Usage: gyp_main.py [options ...] [build_file ...]                                         

gyp_main.py: error: no such option: --no-parallel                                         
gyp ERR! configure error                                                                  
gyp ERR! stack Error: `gyp` failed with exit code: 2                                      
gyp ERR! stack     at ChildProcess.onCpExit (/opt/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)                                            
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)                                 
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)       
gyp ERR! System Linux 3.13.0-63-generic                                                   
gyp ERR! command "node" "/opt/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"                                                              
gyp ERR! cwd /tmp/user/1000/apm-install-dir-11588-16981-1ijtnlc/node_modules/Hydrogen/node_modules/zmq                                                                              
gyp ERR! node -v v0.10.40                                                                 
gyp ERR! node-gyp -v v2.0.2                                                               
gyp ERR! not ok                                                                           
npm ERR! Linux 3.13.0-63-generic                                                          
npm ERR! argv "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/christian/.atom/.apm/.apmrc" "--userconfig" "/home/christian/.atom/.apmrc" "install" "/tmp/user/1000/d-11588-16981-1j3aqmk/package.tgz" "--target=0.22.0" "--arch=x64"                                                       
npm ERR! node v0.10.40                                                                    
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.13.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zmq@2.13.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/user/1000/apm-install-dir-11588-16981-1ijtnlc/npm-debug.log
```

**Comment by n-riesco** [comment]
Possibly related https://github.com/atom/atom/pull/2554

**Comment by ChristianRinn** [comment]
I don't think it is related to the incompability with Python 2.7 anymore because that issue should be solved because while I was tracking down the problem, I successfully installed zmq via ```sudo npm install zmq```.

As far as I can tell the problem is related to outdated node packages in the official repositories from Canonical. I got everything working now by removing all nodejs related repos, updating to a 0.10 version from https://github.com/nodesource/distributions and then installing node-gyp via ```sudo npm install -g node-gyp```. Maybe this helps someone with the same problem.

**Comment by n-riesco** [comment]
I reckon that `sudo npm install -g node-gyp` fixed your issue. See https://github.com/nodejs/node-gyp/pull/441

**Comment by ChristianRinn** [comment]
Thanks for pointing that out. That makes sense to me now.
