### ISSUE TITLE
Can't install on mac

### ISSUE THREAD

**Issue by ericelliott** [willwhitney/hydrogen#142]
I followed the install instructions for mac, but get the following:

```sh
$ PYTHON=python2.7 apm install hydrogen
Installing hydrogen to /Users/eric/.atom/packages ✗

> zmq@2.14.0 install /private/var/folders/4r/vxjdd9_x5gbbdq001b4ctgbh0000gn/T/apm-install-dir-1151029-24081-m9hhkx/node_modules/Hydrogen/node_modules/zmq
> node-gyp rebuild


Package libzmq was not found in the pkg-config search path.
Perhaps you should add the directory containing `libzmq.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libzmq' found
gyp: Call to 'pkg-config libzmq --libs' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/4r/vxjdd9_x5gbbdq001b4ctgbh0000gn/T/apm-install-dir-1151029-24081-m9hhkx/node_modules/Hydrogen/node_modules/zmq
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Darwin 15.0.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/eric/.atom/.apm/.apmrc" "--userconfig" "/Users/eric/.atom/.apmrc" "install" "/private/var/folders/4r/vxjdd9_x5gbbdq001b4ctgbh0000gn/T/d-1151029-24081-odgvlq/package.tgz" "--target=0.34.0" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.14.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zmq@2.14.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/4r/vxjdd9_x5gbbdq001b4ctgbh0000gn/T/apm-install-dir-1151029-24081-m9hhkx/npm-debug.log
```

Looks to me like we also need to link zeromq...

```sh
$ brew install zeromq
Warning: zeromq-4.0.5_2 already installed, it's just not linked
```

Maybe a more detailed troubleshooting doc would be good. =)

**Comment by willwhitney** [comment]
Brew normally would link zeromq; I'm not sure why it didn't this time.

I forget sometimes that this repo has a wiki. Maybe it's time we start using it...

Would you mind adding an entry for this to the troubleshooting page? https://github.com/willwhitney/hydrogen/wiki/Troubleshooting

**Comment by ericelliott** [comment]
Maybe you should link to that from the install guide? =)

**Comment by willwhitney** [comment]
Good call! Link added.
