### ISSUE TITLE
Unable to install nor use atom hydrogen in Python 3

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [willwhitney/hydrogen#156]
Apologies if this has been discussed before, but it looks like `gyp` does *not* support Python 3, so one can't use Hydrogen with it. It looks like [there is a thread](https://bugs.chromium.org/p/gyp/issues/detail?id=36) in Chromium blogs discussing this problem and someone even [submitted a CL](https://codereview.chromium.org/1454433002) (a change-list, i.e. like a PR), but it doesn't seem to have been merged or even reviewed yet.

Just in case, to keep track of this issue here, and make sure I am not missing anything, this is the problem I run into if I try to install `hydrogen` in a Python 3 environment:
 
```
$ apm install hydrogen
Installing hydrogen to /Users/avazquez/.atom/packages ✗

> zmq@2.14.0 install /private/var/folders/yl/bqcgdj3d6ss_mrfkpzxlh89m0000gp/T/apm-install-dir-11611-4541-dzyo1b/node_modules/Hydrogen/node_modules/zmq
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: Python executable "python" is v3.5.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:119:14)
gyp ERR! stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:656:7)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at maybeClose (child_process.js:766:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:979:11)
gyp ERR! stack     at Socket.emit (events.js:95:17)
gyp ERR! stack     at Pipe.close (net.js:466:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/yl/bqcgdj3d6ss_mrfkpzxlh89m0000gp/T/apm-install-dir-11611-4541-dzyo1b/node_modules/Hydrogen/node_modules/zmq
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Darwin 15.3.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/avazquez/.atom/.apm/.apmrc" "--userconfig" "/Users/avazquez/.atom/.apmrc" "install" "/private/var/folders/yl/bqcgdj3d6ss_mrfkpzxlh89m0000gp/T/d-11611-4541-1g62qsv/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.14.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zmq@2.14.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/yl/bqcgdj3d6ss_mrfkpzxlh89m0000gp/T/apm-install-dir-11611-4541-dzyo1b/npm-debug.log
```

**Comment by slavaGanzin** [comment]
@amelio-vazquez-reina  You are right. node-gyp doesn't work with py3. On some systems you need even provide ```--python=/path/to/python2``` to node-gyp.

 But this isn't issue with Hydrogen and and you can find mentioning: *Python 2 (for builds - you can still run Python 3 code)* in **Dependecies** in Readme.md.
