### ISSUE TITLE
Uncaught Error: EBADF: bad file descriptor, write

### ISSUE THREAD

**Issue by jlibin** [willwhitney/hydrogen#22]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.201.0
**System**: Microsoft Windows Server 2008 R2 Standard 
**Thrown From**: [Hydrogen](https://github.com/willwhitney/hydrogen) package, v0.3.7

### Stack Trace

Uncaught Error: EBADF: bad file descriptor, write

```
At fs.js:657

Error: EBADF: bad file descriptor, write
  at Error (native)
  at Object.fs.writeSync (fs.js:657:20)
  at SyncWriteStream.write (fs.js:1906:6)
  at execSync (child_process.js:1372:20)
  at Object.<anonymous> (C:\Users\Administrator\.atom\packages\Hydrogen\lib\paths.coffee:10:12)
  at Object.<anonymous> (C:\Users\Administrator\.atom\packages\Hydrogen\lib\paths.coffee:3:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\Administrator\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Administrator\.atom\packages\Hydrogen\lib\kernel-manager.coffee:6:17)
  at Object.<anonymous> (C:\Users\Administrator\.atom\packages\Hydrogen\lib\kernel-manager.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\Administrator\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Administrator\.atom\packages\Hydrogen\lib\main.coffee:7:17)
  at Object.<anonymous> (C:\Users\Administrator\.atom\packages\Hydrogen\lib\main.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\Administrator\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\Administrator\AppData\Local\atom\app-0.201.0\resources\app.asar\src\package.js:709:34)
  at Package.module.exports.Package.activateConfig (C:\Users\Administrator\AppData\Local\atom\app-0.201.0\resources\app.asar\src\package.js:255:12)
  at PackageDetailView.module.exports.PackageDetailView.activate (C:\Users\Administrator\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:163:26)
  at PackageDetailView.module.exports.PackageDetailView.initialize (C:\Users\Administrator\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:146:12)
  at PackageDetailView.View (C:\Users\Administrator\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
  at new PackageDetailView (C:\Users\Administrator\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:38:54)
  at C:\Users\Administrator\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\settings-view\lib\settings-view.js:255:22
  at SettingsView.module.exports.SettingsView.getOrCreatePanel (C:\Users\Administrator\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\settings-view\lib\settings-view.js:260:19)
  at SettingsView.module.exports.SettingsView.showPanel (C:\Users\Administrator\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\settings-view\lib\settings-view.js:296:24)
  at space-pen-div.<anonymous> (C:\Users\Administrator\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\settings-view\lib\package-card.js:214:26)
  at space-pen-div.jQuery.event.dispatch (C:\Users\Administrator\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at space-pen-div.elemData.handle (C:\Users\Administrator\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
  2x -7:16.8.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -7:02.6.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -6:55.9.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  6x -6:55.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:43.5.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
 18x -5:15.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:57.5.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:51.1.0 core:move-up (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:49.4.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:20.2.0 core:backspace (atom-text-editor.editor.is-focused)
  4x -2:19.6.0 core:move-right (atom-text-editor.editor.is-focused)
  3x -2:14.3.0 core:backspace (atom-text-editor.editor.is-focused)
 21x -2:09.7.0 core:select-up (atom-text-editor.editor.is-focused)
     -1:47.2.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "chester-atom-syntax"
    ],
    "disabledPackages": [
      "autocomplete-python"
    ]
  },
  "Hydrogen": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.27.6
autocomplete-plus-python-jedi, v0.3.5
chester-atom-syntax, v0.1.1
language-r, v0.2.0
script, v2.23.0
web-browser, v1.4.4

# Dev
No dev packages
```

**Comment by rgbkrk** [comment]
Booting up a Windows Server now to try this out.

Per https://github.com/TypeStrong/atom-typescript/issues/33, can you try fully quitting and restarting Atom?

**Comment by rgbkrk** [comment]
This is down to just the `execSync` trying to find Python. It's weird.

![screenshot 2015-05-23 09 20 37](https://cloud.githubusercontent.com/assets/836375/7784486/0e9c48de-012d-11e5-8b1e-f2a78e166a56.png)

**Comment by rgbkrk** [comment]
Seems like it can't find the Python I installed. :(

![screenshot 2015-05-23 09 31 48](https://cloud.githubusercontent.com/assets/836375/7784532/7e314cd4-012e-11e5-8740-1ded1ad57128.png)

**Comment by willwhitney** [comment]
Oh my god, I just figured out what's going on.

It's not that it can't find Python.

It's trying to write to an output pipe for all of Atom, which doesn't exist. Unless you start Atom with `atom -w` to make it not detach. Then it writes the output of, for example, `python --version` to the `cmd` you launched Atom from.

**Comment by willwhitney** [comment]
Seems to not be a problem when using `spawn` instead of `exec`: 

![screenshot 2015-05-23 19 22 15](https://cloud.githubusercontent.com/assets/597829/7786064/1cb95764-0181-11e5-8ea3-c80e9c8b5d1f.png)

**Comment by rgbkrk** [comment]
WTF and thank you.

**Comment by willwhitney** [comment]
Per conversation in #19, I think this is solved. Let me know if it's not and we'll reopen and look into it again.
