### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by spencerlyon2** [willwhitney/hydrogen#5]
[Enter steps to reproduce below:]

Happens on any python or Julia file whenever I try to run _any_ code.

**Atom Version**: 0.199.0
**System**: Mac OS X 10.10.3
**Thrown From**: [Hydrogen](https://github.com/willwhitney/hydrogen) package, v0.1.3

### Stack Trace

Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

```
At /Users/sglyon/.atom/packages/Hydrogen/lib/kernel-manager.coffee:40

TypeError: Cannot read property 'toLowerCase' of undefined
  at /Users/sglyon/.atom/packages/Hydrogen/lib/kernel-manager.coffee:40:73
  at arrayFilter (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:1427:13)
  at Function.filter (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:6365:14)
  at Object.module.exports.KernelManager.getKernelInfoForLanguage (/Users/sglyon/.atom/packages/Hydrogen/lib/kernel-manager.coffee:39:29)
  at Object.module.exports.KernelManager.languageHasKernel (/Users/sglyon/.atom/packages/Hydrogen/lib/kernel-manager.coffee:48:16)
  at Object.module.exports.AtomRepl.run (/Users/sglyon/.atom/packages/Hydrogen/lib/main.coffee:138:26)
  at atom-text-editor.subscriptions.add.atom.commands.add.hydrogen:run (/Users/sglyon/.atom/packages/Hydrogen/lib/main.coffee:25:33)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
     -0:02.2.0 hydrogen:run (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:00.2.0 editor:select-to-first-character-of-line (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-eighties-dark"
    ],
    "disabledPackages": [
      "emmet",
      "linter-pyflakes",
      "rst-preview",
      "minimap",
      "notebook",
      "timekeeper"
    ],
    "PATH": "/usr/local/heroku/bin:/Users/sglyon/anaconda/bin:/Users/sglyon/src/julia/julia/usr/bin:/Users/sglyon/bin:/Users/sglyon/.cabal/bin:/usr/local/bin:/usr/local/sbin:/usr/texbin:/usr/local/gocode/bin:/Users/sglyon/google-cloud-sdk/bin:/Applications/Dynare/4.4.3/dynare  :/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/texbin",
    "useReactEditor": true,
    "projectHome": "/Users/sglyon/School/NYU",
    "destroyEmptyPanes": false
  }
}
```

### Installed Packages

```coffee
# User
Hydrogen, v0.1.3
atom-django, v0.2.1
atomatigit, v1.3.0
autocomplete-paths, v1.0.2
base16-eighties-dark, v2.1.1
color-picker, v1.7.0
command-logger, v0.23.0
editor-stats, v0.17.0
language-julia, v0.8.1
language-latex, v0.6.1
language-matlab, v0.1.0
language-r, v0.2.0
language-restructuredtext, v0.5.0
linter, v0.12.2
project-manager, v1.15.5
remote-edit, v1.7.2
remote-sync, v2.4.1
script, v2.23.0
syntax-settings, v0.7.1
travis-ci-status, v0.14.1
vim-mode, v0.46.0
wakatime, v4.0.9

# Dev
No dev packages
```

**Comment by willwhitney** [comment]
I think this is happening because either 1. Atom doesn't know what language the file you're editing is in, or 2. the kernels you're using don't declare their language.

Does the language show up in the status bar of Atom, like this?

![atom status bar](http://f.cl.ly/items/2a0d1K2J2c362T1g1u2w/Screenshot%202015-05-18%2011.40.54.png)

If it does, would you mind updating to the version I just released, then popping open the dev tools and telling me what it says next to "Available kernels" when you try to run something?

**Comment by spencerlyon2** [comment]
Yep, I see the same thing in the status bar.

I opened up the dev tools, but don't know how to ask it for "Available Kernels"...

**Comment by spencerlyon2** [comment]
Found it:

```
Available kernels: Array[6]0: 
Objectargv: Array[5]display_name: "R"__proto__: Object1: 
Objectargv: Array[5]display_name: "Julia 0.3.6"language: "julia"__proto__: Object2: 
Objectargv: Array[5]display_name: "Julia 0.3.6"language: "julia"__proto__: Object3: 
Objectargv: Array[5]display_name: "Julia 0.3.8"language: "julia"__proto__: Object4: 
Objectargv: Array[5]display_name: "Julia 0.4.0-dev"language: "julia"__proto__: Object5: 
Objectargv: Array[5]display_name: "Python 3"language: "python"__proto__: Objectlength: 6__proto__: Array[0]
```

**Comment by willwhitney** [comment]
@spencerlyon2 I think the issue is that the R kernel isn't giving me a language field. Just pushed a patch — please update and give it a shot, and let me know if it's still broken!

**Comment by spencerlyon2** [comment]
That worked! Thanks

**Comment by spencerlyon2** [comment]
... well that works for julia and python, but not R.

When I try to run code in an R file it tells me that there is no kernel for r.

Here are the contents of `~/.ipython/kernels/ir/kernel.json`:

```json
{"argv": ["R","-e","IRkernel::main()","--args","{connection_file}"],
 "display_name":"R"
}
```

**Comment by willwhitney** [comment]
Whoops, forgot to make the other two lines of that change. Update and try it again?

I'm now using the `display_name` if the kernelspec doesn't declare a `language`.

**Comment by rgbkrk** [comment]
@takluyver should IRkernel be declaring a language or is that an optional field?

**Comment by takluyver** [comment]
Yes, I think we should be declaring a language. The spec changed a couple of times while we were developing IPython 3, and I guess I missed that one.
