### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getGrammar' of undefined

### ISSUE THREAD

**Issue by crazzle** [willwhitney/hydrogen#83]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [Hydrogen](https://github.com/willwhitney/hydrogen) package, v0.4.2

### Stack Trace

Uncaught TypeError: Cannot read property 'getGrammar' of undefined

```
At /Users/mark/.atom/packages/Hydrogen/lib/main.coffee:160

TypeError: Cannot read property 'getGrammar' of undefined
  at Object.module.exports.Hydrogen.run (/Users/mark/.atom/packages/Hydrogen/lib/main.coffee:160:25)
  at atom-text-editor.subscriptions.add.atom.commands.add.hydrogen:run (/Users/mark/.atom/packages/Hydrogen/lib/main.coffee:41:33)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -3:32.5.0 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
     -3:31.1.0 hydrogen:run (atom-text-editor.editor.is-focused)
     -3:29.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -3:27.8.0 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
     -3:27.3.0 hydrogen:run (atom-text-editor.editor.is-focused)
     -3:22.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:20.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -3:18.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -3:12.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:12.4.0 hydrogen:toggle-watches (atom-text-editor.editor)
     -2:54 editor:newline (atom-text-editor.editor.watch-input.is-focused)
     -2:53.2.0 core:backspace (atom-text-editor.editor.watch-input.is-focused)
     -2:44.4.0 hydrogen:run (atom-text-editor.editor.is-focused)
     -2:42.7.0 core:move-up (atom-text-editor.editor.is-focused)
  3x -2:38.7.0 core:move-down (atom-text-editor.editor.is-focused)
  6x -2:30.3.0 hydrogen:run (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-javac",
      "linter-pylint",
      "linter-ruby",
      "linter-scalac",
      "linter-chktex"
    ]
  },
  "Hydrogen": {}
}
```

### Installed Packages

```coffee
# User
Ensime, vundefined
Hydrogen, v0.4.2
autocomplete-bibtex, v0.5.7
language-arduino, v0.3.0
language-latex, v0.6.1
language-scala, v1.1.3
latex, v0.25.0
linter, v1.2.3
minimap, v4.11.2
minimap-git-diff, v4.1.6
scala-format, v0.1.8
tree-view-git-status, v0.1.1

# Dev
No dev packages
```

**Comment by willwhitney** [comment]
Did you figure out what was causing this?

**Comment by crazzle** [comment]
Hi - I am not sure as I cannot reproduce it.
The error was caused when I accidentally had the settings tab open and in focus while trying to run the plugin with Hydrogen: Run.
But that seems to be a misbehavior in atom that is not reproducible.

**Comment by willwhitney** [comment]
OK, thanks!

**Comment by alekzvik** [comment]
Had the same error.

Steps to reproduce:
1. Open python file
2. Add few watches
3. Close python file (no open tabs left)
4. Run code in watches pane
