### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by smason** [willwhitney/hydrogen#94]
I wanted to hide a `%matplotlib inline` from the normal interpreter so I put the following at the top of my code:

    # %matplotlib inline

in order that I could select the command and hence only run it within Atom.

To reproduce, paste the above anywhere in a python document, select it and hit run.  I was hoping to select everything apart from the `#` and hence evaluate just the ipython escape, but that's not needed to reproduce the bug for me.

**Atom Version**: 1.0.6
**System**: Mac OS X 10.11
**Thrown From**: [Hydrogen](https://github.com/willwhitney/hydrogen) package, v0.4.4

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:419

TypeError: Cannot read property 'length' of undefined
    at TextBuffer.module.exports.TextBuffer.lineLengthForRow (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:419:29)
    at Object.module.exports.Hydrogen.insertResultBubble (/Users/smason/.atom/packages/Hydrogen/lib/main.coffee:138:27)
    at /Users/smason/.atom/packages/Hydrogen/lib/main.coffee:214:30
    at Object.module.exports.Hydrogen.startKernelIfNeeded (/Users/smason/.atom/packages/Hydrogen/lib/main.coffee:307:18)
    at Object.module.exports.Hydrogen.run (/Users/smason/.atom/packages/Hydrogen/lib/main.coffee:197:21)
    at atom-text-editor.subscriptions.add.atom.commands.add.hydrogen:run (/Users/smason/.atom/packages/Hydrogen/lib/main.coffee:45:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
```

### Commands

```
     -0:22.2.0 hydrogen:run (atom-text-editor.editor.is-focused)
     -0:16 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:15 hydrogen:run (atom-text-editor.editor.is-focused)
     -0:12.9.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:12.9.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:11.7.0 hydrogen:clear-results (atom-text-editor.editor.is-focused)
  3x -0:10.8.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:10.4.0 core:move-right (atom-text-editor.editor.is-focused)
  5x -0:09.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:08.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:07.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:06.2.0 hydrogen:clear-results (atom-text-editor.editor.is-focused)
     -0:04.1.0 core:move-to-top (atom-text-editor.editor.is-focused)
     -0:03.0 pane:show-next-item (atom-text-editor.editor.is-focused)
     -0:01.9.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:00.7.0 hydrogen:run (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "followSymlinks": false,
    "audioBeep": false,
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Hydrogen, v0.4.4
autocomplete-python, v0.5.3
language-latex, v0.6.1
latex, v0.25.0
linter-chktex, v1.0.0

# Dev
No dev packages
```

**Comment by igorbb** [comment]
Same issues With Linux.

**Atom Version**: 1.0.7
**System**: linux 4.1.5-1-ARCH
**Thrown From**: [Hydrogen](https://github.com/willwhitney/hydrogen) package, v0.4.4


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:419

TypeError: Cannot read property 'length' of undefined
    at TextBuffer.module.exports.TextBuffer.lineLengthForRow (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:419:29)
    at Object.module.exports.Hydrogen.insertResultBubble (/home/igorbb/.atom/packages/Hydrogen/lib/main.coffee:138:27)
    at /home/igorbb/.atom/packages/Hydrogen/lib/main.coffee:214:30
    at Object.module.exports.Hydrogen.startKernelIfNeeded (/home/igorbb/.atom/packages/Hydrogen/lib/main.coffee:307:18)
    at Object.module.exports.Hydrogen.run (/home/igorbb/.atom/packages/Hydrogen/lib/main.coffee:197:21)
    at atom-text-editor.subscriptions.add.atom.commands.add.hydrogen:run (/home/igorbb/.atom/packages/Hydrogen/lib/main.coffee:45:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:177:20)
```

### Commands

```
     -1:45.7.0 core:paste (atom-text-editor.editor.is-focused)
     -1:44.1.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -1:43.8.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:43.8.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:43.8.0 editor:indent (atom-text-editor.editor.is-focused)
  8x -1:29.3.0 core:delete (atom-text-editor.editor.is-focused)
     -1:19.7.0 core:save (atom-text-editor.editor.is-focused)
     -1:17.2.0 hydrogen:show-kernel-commands (atom-text-editor.editor.is-focused)
     -1:14 core:select-all (atom-text-editor.editor.is-focused)
     -1:13.2.0 hydrogen:run (atom-text-editor.editor.is-focused)
  2x -1:03.7.0 hydrogen:show-kernel-commands (atom-text-editor.editor.is-focused)
 10x -0:52.8.0 hydrogen:run (atom-text-editor.editor.is-focused)
     -0:06.6.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -0:06.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:02.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:00.6.0 hydrogen:run (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true
  },
  "Hydrogen": {}
}
```

### Installed Packages

```coffee
# User
Hydrogen, v0.4.4
atom-beautify, v0.28.11
autocomplete-python, v0.5.3
linter, v1.4.3
linter-pep8, v1.0.1

# Dev
No dev packages
```
